### ISSUE TITLE
Cannot define multiple included blocks for a Concern 

### ISSUE THREAD

**Issue by emilioforrer** [the-teacher/the_role#68]
Hi,

Im using `the_role` for a project with rails 4.2 and  just hited this issue while running `bundle exec rails g the_role admin`, here's the stacktrace:

```
/home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/the_role-2.5.4/app/models/concerns/role.rb:18:in `<module:Role>'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/the_role-2.5.4/app/models/concerns/role.rb:2:in `<module:TheRole>'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/the_role-2.5.4/app/models/concerns/role.rb:1:in `<top (required)>'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/the_role-2.5.4/lib/generators/the_role/the_role_generator.rb:44:in `create_admin_role'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/the_role-2.5.4/lib/generators/the_role/the_role_generator.rb:14:in `generate_controllers'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/developer/.rvm/gems/ruby-2.0.0-p481@rails4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
```

**Comment by the-teacher** [comment]
Hello! Thank you for report!

1) try to install code from master branch
2) this message looks familiar. I'll check and fix it, but I need few days to finish current work.

I think reason of error is here: https://github.com/the-teacher/the_role/blob/master/lib/the_role.rb#L35
I have to use autoload instead require. Same problem was fixed for another my gem.

**Comment by emilioforrer** [comment]
Ya it is an autoload trouble  but, Im using the gem inside an Engine that am making and the error happened because didn't run the `bundle exec rails g the_role install` on the project. **After that it worked**.

**Comment by the-teacher** [comment]
awesome! but it still be fixed. thanks a lot!

**Comment by fuksman** [comment]
Hi. I have the same problem when trying to deploy to staging environment. Can you say when you will be able to fix it? (or how I can make a hotfix in my project)

**Comment by the-teacher** [comment]
@fuksman @emilioforrer I fixed autoload problem. Please install gem from `master` branch and test it.
I have few broken tests for controllers, but the_role API works will. I hope it will work.

I will be waiting for your reports.
Thanks a lot!

**Comment by fuksman** [comment]
@the-teacher everything is ok, thank you for your work!

**Comment by the-teacher** [comment]
## Attention! Last stable 2.X version can be installed with

```ruby
gem 'the_role',
  github: 'TheRole/TheRoleApi',
  tag: 'v2.6'
```

**Right now we working on TheRole 3.0**
